if(localStorage.getItem('data') === null){
    localStorage.setItem('activ', JSON.stringify([]))
    localStorage.setItem('skip', JSON.stringify([]))
    localStorage.setItem('complet', JSON.stringify([]))
}

if(localStorage.getItem('data') === null || JSON.parse(localStorage.getItem('data')).length === 0){
    const questDatabase = [
    {
        id: 1,
        title: "Комплимент коллеге",
        description: "Сделайте искренний комплимент профессиональному качеству вашего коллеги или знакомого.",
        difficulty: "easy",
        category: "communication"
    },
    {
        id: 2,
        title: "Пять благодарностей",
        description: "Запишите 5 вещей, за которые вы благодарны сегодняшнему дню, и объясните почему.",
        difficulty: "easy",
        category: "introspection"
    },
    {
        id: 3,
        title: "Абстрактный натюрморт",
        description: "Нарисуйте любой предмет со стола, используя только геометрические фигуры (треугольники, круги).",
        difficulty: "middle",
        category: "creation"
    },
    {
        id: 4,
        title: "Разговор в очереди",
        description: "Заведите короткий непринужденный разговор с незнакомым человеком в общественном месте.",
        difficulty: "middle",
        category: "communication"
    },
    {
        id: 5,
        title: "Анализ привычки",
        description: "Выберите одну свою вредную привычку и распишите по пунктам: какой триггер её запускает и чем её можно заменить.",
        difficulty: "hard",
        category: "introspection"
    },
    {
        id: 6,
        title: "Сказка за 5 минут",
        description: "Придумайте и запишите короткую сказку, в которой главными героями будут вилка и кактус.",
        difficulty: "middle",
        category: "creation"
    },
    {
        id: 7,
        title: "Цифровой детокс",
        description: "Проведите 3 часа без использования любых гаджетов и интернета, наблюдая за своими ощущениями.",
        difficulty: "hard",
        category: "introspection"
    },
    {
        id: 8,
        title: "Слушатель",
        description: "В течение 10 минут внимательно слушайте собеседника, не перебивая и не давая советов, только задавая уточняющие вопросы.",
        difficulty: "middle",
        category: "communication"
    },
    {
        id: 9,
        title: "Новый логотип",
        description: "Придумайте и набросайте на бумаге новый логотип для вашего любимого фрукта.",
        difficulty: "easy",
        category: "creation"
    },
    {
        id: 10,
        title: "Карта страхов",
        description: "Составьте список из 3 своих главных страхов и напишите план из 2 шагов для преодоления каждого из них.",
        difficulty: "hard",
        category: "introspection"
    },
    { id: 11, title: "Три вопроса", description: "Задайте другу или коллеге 3 личных, но уместных вопроса о его мечтах, страхах или мотивации. Выслушайте ответы без оценок.", difficulty: "easy", category: "communication" },
{ id: 12, title: "Отказ вежливо", description: "Вежливо откажите кому-то в небольшой просьбе (без оправданий на 5 минут). Просто: 'Нет, не могу, но спасибо, что обратились'." , difficulty: "middle", category: "communication" },
{ id: 13, title: "Зеркало эмоций", description: "В разговоре повторите позу и тон собеседника 2-3 раза (не демонстративно). Заметьте, изменилось ли его расположение.", difficulty: "middle", category: "communication" },
{ id: 14, title: "Просьба о помощи", description: "Попросите о реальной небольшой помощи (неудобной для вас). Например, помочь донести сумку или объяснить тему.", difficulty: "easy", category: "communication" },
{ id: 15, title: "Комплимент незнакомцу", description: "Сделайте искренний комплимент незнакомому человеку (прическа, куртка, походка) без флирта.", difficulty: "middle", category: "communication" },
{ id: 16, title: "Извинение", description: "Вспомните ситуацию, где вы были неправы, и извинитесь перед человеком (лично или в сообщении, если встреча невозможна).", difficulty: "hard", category: "communication" },
{ id: 17, title: "Вопрос почему", description: "В течение дня каждого, кто скажет 'всё нормально', спросите: 'А почему именно нормально?'", difficulty: "easy", category: "communication" },
{ id: 18, title: "Без я-сообщений", description: "Постройте разговор так, чтобы 5 минут не использовать фразы 'я думаю', 'мне кажется', 'я хочу'. Только факты и вопросы.", difficulty: "hard", category: "communication" },
{ id: 19, title: "История имени", description: "Спросите у 3 человек историю их имени — почему родители так назвали, нравится ли им.", difficulty: "easy", category: "communication" },
{ id: 20, title: "Несогласие мягко", description: "Мягко выразите несогласие с чьим-то мнением, начиная с 'Я понимаю твою логику, но вижу это иначе...'", difficulty: "middle", category: "communication" },
{ id: 21, title: "Чужой интерес", description: "Попросите человека рассказать о его хобби, которое вам неинтересно. Послушайте 5 минут с реальным любопытством.", difficulty: "middle", category: "communication" },
{ id: 22, title: "Спасибо за критику", description: "Получив конструктивную критику, скажите только 'Спасибо, я подумаю над этим' без оправданий.", difficulty: "hard", category: "communication" },
{ id: 23, title: "Телефонный звонок", description: "Позвоните кому-то вместо сообщения. Поговорите хотя бы 2 минуты о бытовых вещах.", difficulty: "easy", category: "communication" },
{ id: 24, title: "Пауза 3 секунды", description: "Перед каждым ответом в разговоре делайте паузу в 3 секунды. Заметьте, как изменилось качество ваших ответов.", difficulty: "middle", category: "communication" },
{ id: 25, title: "Слабое место", description: "Расскажите близкому человеку о своей неуверенности в какой-то сфере (без самобичевания, просто факт).", difficulty: "hard", category: "communication" },
{ id: 26, title: "Подстройка к темпу", description: "Подстройте скорость речи и громкость под собеседника в течение 10 минут.", difficulty: "easy", category: "communication" },
{ id: 27, title: "Ошибка вслух", description: "Признайтесь вслух при свидетелях: 'Я ошибся в [ситуация]'. Без оправданий, просто признание.", difficulty: "hard", category: "communication" },
{ id: 28, title: "Вопросы открытые", description: "В разговоре задавайте только открытые вопросы (начинающиеся с Как? Почему? Что ты думаешь о...?), закрытые исключите.", difficulty: "middle", category: "communication" },
{ id: 29, title: "Негатив без жертвы", description: "Пожалуйтесь кому-то на ситуацию, не обвиняя конкретного человека. Только факты и эмоции.", difficulty: "middle", category: "communication" },
{ id: 30, title: "Завершение разговора", description: "Вежливо и твёрдо завершите ненужный разговор фразой 'Было приятно, но мне пора'.", difficulty: "easy", category: "communication" },
{ id: 31, title: "Прокрастинация", description: "Запишите 3 дела, которые вы откладываете, и точную причину по каждому (страх, лень, неумение, перфекционизм).", difficulty: "easy", category: "introspection" },
{ id: 32, title: "Пять почему", description: "Возьмите одну проблему и спросите себя 'почему?' 5 раз, пока не докопаетесь до корня.", difficulty: "middle", category: "introspection" },
{ id: 33, title: "Идеальный день", description: "Опишите по минутам ваш идеальный день через 5 лет. Без фантастики, реалистично.", difficulty: "middle", category: "introspection" },
{ id: 34, title: "Чувство вины", description: "Вспомните 3 ситуации, где вы чувствуете вину. По каждой решите: это объективная вина или навязанная извне?", difficulty: "hard", category: "introspection" },
{ id: 35, title: "Ресурсное состояние", description: "Вспомните 3 действия, которые гарантированно поднимают вам энергию. Запланируйте одно на завтра.", difficulty: "easy", category: "introspection" },
{ id: 36, title: "10 лет назад", description: "Напишите письмо себе 10-летней давности. Что бы вы посоветовали? Что похвалили бы?", difficulty: "hard", category: "introspection" },
{ id: 37, title: "Зависть как компас", description: "Вспомните человека, которому вы завидуете. Что конкретно в нём вызывает зависть? Это ваша несбытая ценность.", difficulty: "middle", category: "introspection" },
{ id: 38, title: "Пустые траты", description: "Проанализируйте последние 3 импульсивные покупки. Что вы чувствовали до, во время и после?", difficulty: "easy", category: "introspection" },
{ id: 39, title: "Роли в жизни", description: "Перечислите все ваши социальные роли (работник, родитель, друг и т.д.). Оцените удовлетворённость каждой по 10-балльной шкале.", difficulty: "middle", category: "introspection" },
{ id: 40, title: "Правила-ограничения", description: "Запишите 5 внутренних правил, которые вас ограничивают ('я не могу', 'мне нельзя'). Поставьте под сомнение каждое.", difficulty: "hard", category: "introspection" },
{ id: 41, title: "Сожаление", description: "Назовите одно главное сожаление. Что вы можете сделать прямо сейчас, чтобы оно перестало быть сожалением?", difficulty: "hard", category: "introspection" },
{ id: 42, title: "Энергетические воры", description: "Перечислите 3 занятия или 3 людей, после которых вы чувствуете упадок сил. Как сократить контакт?", difficulty: "easy", category: "introspection" },
{ id: 43, title: "Зона роста", description: "Назовите навык, который вы избегаете развивать, потому что 'не ваше'. Это точно не ваше или просто страшно?", difficulty: "middle", category: "introspection" },
{ id: 44, title: "Обида", description: "Вспомните обиду, которую носите дольше года. Зачем вы её держите? Что вы получаете от этой обиды?", difficulty: "hard", category: "introspection" },
{ id: 45, title: "Сравнение с другими", description: "С кем вы себя сравниваете чаще всего? Запишите 3 отличия вас от этого человека в вашу пользу.", difficulty: "easy", category: "introspection" },
{ id: 46, title: "Сканирование тела", description: "В течение 5 минут мысленно пройдитесь по всему телу от макушки до стоп. Где зажимы? Просто заметить.", difficulty: "easy", category: "introspection" },
{ id: 47, title: "Саботаж успеха", description: "Вспомните ситуацию, когда вы почти достигли цели, но что-то 'случилось'. Как вы сами саботировали себя?", difficulty: "hard", category: "introspection" },
{ id: 48, title: "Ценности топ-5", description: "Из списка 20 ценностей (свобода, безопасность, любовь и т.д.) выберите 5 главных. Проверьте, живёте ли вы им.", difficulty: "middle", category: "introspection" },
{ id: 49, title: "Маски", description: "В каких ситуациях вы надеваете 'маску' (сильного, весёлого, крутого)? Что под ней?", difficulty: "middle", category: "introspection" },
{ id: 50, title: "Последний год", description: "Что хорошего случилось за последний год? Запишите 10 пунктов (даже мелочи: вкусный кофе, хорошая погода).", difficulty: "easy", category: "introspection" },
{ id: 51, title: "Пластилиновая эмоция", description: "Слепите из пластилина или любого подручного материала (тесто, глина) ваше сегодняшнее настроение в абстрактной форме.", difficulty: "easy", category: "creation" },
{ id: 52, title: "Монохромный коллаж", description: "Создайте коллаж из вырезок/фотографий только одного цвета (например, всё синее). Тема: 'Покой' или 'Гнев' на выбор.", difficulty: "middle", category: "creation" },
{ id: 53, title: "Инструкция для робота", description: "Напишите пошаговую инструкцию на 10 шагов 'Как заварить чай' для инопланетянина, который не знает, что такое кружка, вода или чай.", difficulty: "easy", category: "creation" },
{ id: 54, title: "Фото три предмета", description: "Сделайте художественное фото трёх случайных предметов на вашем столе. Правило: никакого прямого света и центральной композиции.", difficulty: "easy", category: "creation" },
{ id: 55, title: "Название для чувства", description: "Придумайте новое слово для чувства, у которого нет названия (например, 'печаль от того, что красивое место изменилось'). Опишите его.", difficulty: "middle", category: "creation" },
{ id: 56, title: "Колыбельная", description: "Напишите текст колыбельной (6-8 строк) для взрослого человека, который не может уснуть от тревоги.", difficulty: "middle", category: "creation" },
{ id: 57, title: "Рецепт бутерброда", description: "Придумайте рецепт абсурдного, но теоретически съедобного бутерброда. Нарисуйте его или опишите словами.", difficulty: "easy", category: "creation" },
{ id: 58, title: "Чёрно-белый рисунок", description: "Нарисуйте что угодно, используя только чёрную ручку и технику штриховки (без линий-контуров).", difficulty: "middle", category: "creation" },
{ id: 59, title: "Маршрут звуков", description: "Запишите аудиодневник из 5 звуков вашего дня (шаги, кофемашина, ветер). Смонтируйте в 1-минутную композицию.", difficulty: "hard", category: "creation" },
{ id: 60, title: "Диалог предметов", description: "Напишите короткий диалог между утренним будильником и чашкой кофе. Каждый говорит своим 'голосом'.", difficulty: "easy", category: "creation" },
{ id: 61, title: "Абстракция настроения", description: "Нарисуйте 5 маленьких абстрактных картинок для 5 разных настроений (радость, злость, спокойствие, тревога, скука).", difficulty: "middle", category: "creation" },
{ id: 62, title: "Переделка стиха", description: "Возьмите известное стихотворение (2-4 строки) и перепишите его, заменив все существительные на противоположные по смыслу.", difficulty: "middle", category: "creation" },
{ id: 63, title: "Комикс-одностраничник", description: "Нарисуйте комикс из 4 панелей на тему 'Как я решил мелкую проблему сегодня'. Без слов или с минимальными подписями.", difficulty: "hard", category: "creation" },
{ id: 64, title: "Шрифт из тела", description: "Сфотографируйте свою руку/пальцы так, чтобы они образовывали букву. Составьте слово из 3-4 таких 'букв'.", difficulty: "easy", category: "creation" },
{ id: 65, title: "Сон как искусство", description: "Вспомните обрывок недавнего сна. Нарисуйте или опишите его как сюрреалистическую сцену (без логики).", difficulty: "middle", category: "creation" },
{ id: 66, title: "Ода скуке", description: "Напишите короткое (4-6 строк) хвалебное стихотворение скуке как состоянию, которое полезно для творчества.", difficulty: "easy", category: "creation" },
{ id: 67, title: "Танцевальное правило", description: "Придумайте одно простое танцевальное движение (например, 'правой рукой показываем волну, левой — круг'). Запишите его на видео на 5 секунд.", difficulty: "easy", category: "creation" },
{ id: 68, title: "Архитектура чувства", description: "Нарисуйте здание, которое выражает чувство 'одиночество' или 'надежда'. Только внешний вид, никаких людей.", difficulty: "middle", category: "creation" },
{ id: 69, title: "Стиль под музыку", description: "Включите любую незнакомую инструментальную музыку. Нарисуйте то, что видите 'внутри' музыки (цвета, формы).", difficulty: "easy", category: "creation" },
{ id: 70, title: "Письмо из будущего", description: "Напишите открытку себе из 2030 года, где вы благодарите себя-сегодняшнего за одно решение.", difficulty: "middle", category: "creation" },
{ id: 71, title: "Мусор не мимо", description: "Поднимите один мусор на улице (не свой) и выбросите в урну. Сделайте это без показухи.", difficulty: "easy", category: "kindness" },
{ id: 72, title: "Уступи место", description: "Уступите место в транспорте или очереди тому, кому это реально нужно (пожилой, с ребёнком, уставший).", difficulty: "easy", category: "kindness" },
{ id: 73, title: "Поддержка молча", description: "Просто посидите рядом с человеком, которому плохо, не говоря ни слова. 5 минут тихого присутствия.", difficulty: "middle", category: "kindness" },
{ id: 74, title: "Покормить бездомное животное", description: "Купите небольшой корм и покормите бездомную кошку или собаку (если есть возможность и безопасно).", difficulty: "easy", category: "kindness" },
{ id: 75, title: "Невидимая помощь", description: "Сделайте что-то полезное, чтобы никто не узнал (помыть чашки на работе, заправить постель соседу по общежитию).", difficulty: "middle", category: "kindness" },
{ id: 76, title: "Честные чаевые", description: "Оставьте чаевые больше обычного и скажите 'за отличную работу' (не просто 'сдачи не надо').", difficulty: "easy", category: "kindness" },
{ id: 77, title: "Отзыв для малого бизнеса", description: "Напишите хороший отзыв на картах для небольшой местной кофейни/мастерской, где вам понравилось.", difficulty: "easy", category: "kindness" },
{ id: 78, title: "Предложение помощи", description: "Увидев, что человеку тяжело (несёт сумки, растерян), подойдите и спросите: 'Вам помочь?' Не делайте за него, просто спросите.", difficulty: "middle", category: "kindness" },
{ id: 79, title: "Комплимент ребёнку", description: "Сделайте искренний комплимент ребёнку друзей/родственников (не внешности, а поступку или качеству: 'ты очень настойчивый').", difficulty: "easy", category: "kindness" },
{ id: 80, title: "Пропусти вперёд", description: "В супермаркете пропустите вперёд человека с 1-2 товарами, даже если у вас их больше.", difficulty: "easy", category: "kindness" },
{ id: 81, title: "Поддержка коллеги", description: "Напишите коллеге (не лучшему другу) сообщение: 'Заметил, как ты круто сделал [конкретное дело]'", difficulty: "easy", category: "kindness" },
{ id: 82, title: "Без жалоб день", description: "Проживите день, не жалуясь ни на что вслух. Если хочется пожаловаться — переформулируйте как просьбу или действие.", difficulty: "hard", category: "kindness" },
{ id: 83, title: "Старые вещи", description: "Отложите 3 вещи в хорошем состоянии, которые не носите/не используете. Отвезите в благотворительный контейнер.", difficulty: "middle", category: "kindness" },
{ id: 84, title: "Спасибо маме/близкому", description: "Скажите 'спасибо за...' с конкретикой (не просто 'за всё'), человеку, который вас растил.", difficulty: "easy", category: "kindness" },
{ id: 85, title: "Помощь соседу", description: "Помогите соседу донести пакеты до двери или придержите дверь с улыбкой.", difficulty: "easy", category: "kindness" },
{ id: 86, title: "Стакан воды", description: "Выпейте стакан воды сразу после пробуждения, до чая/кофе. Засеките, прошло ли 15 минут без другой жидкости.", difficulty: "easy", category: "health" },
{ id: 87, title: "Растяжка 5 минут", description: "Сделайте 5-минутную растяжку всех основных групп мышц. Без телефона, просто медленные движения.", difficulty: "easy", category: "health" },
{ id: 88, title: "Прогулка без цели", description: "Выйдите на 20 минут гулять без телефона и без маршрута. Куда глаза глядят.", difficulty: "middle", category: "health" },
{ id: 89, title: "Жвачка для челюсти", description: "Пожуйте жевательную резинку без сахара 5 минут — это снижает кортизол и расслабляет челюсть.", difficulty: "easy", category: "health" },
{ id: 90, title: "Глубокое дыхание", description: "Подышите по квадрату: вдох 4 сек — задержка 4 — выдох 4 — задержка 4. 10 циклов.", difficulty: "easy", category: "health" },
{ id: 91, title: "Убираем телефон из спальни", description: "Оставьте телефон заряжаться в другой комнате на одну ночь. Запишите, как засыпалось и проснулось.", difficulty: "hard", category: "health" },
{ id: 92, title: "Овощ или фрукт", description: "Съешьте один овощ или фрукт в качестве перекуса вместо привычного мусора.", difficulty: "easy", category: "health" },
{ id: 93, title: "Осанка за ноутбуком", description: "Каждые 20 минут проверяйте осанку. Поставьте таймер на час. Сколько раз поймали себя в позе креветки?", difficulty: "middle", category: "health" },
{ id: 94, title: "Сон на час раньше", description: "Лягте спать на 60 минут раньше обычного. Телефон вне досягаемости.", difficulty: "hard", category: "health" },
{ id: 95, title: "Массаж стоп", description: "Помассируйте стопы 3 минуты (можно теннисным мячиком). Особенно центр стопы — связан с надпочечниками.", difficulty: "easy", category: "health" },
{ id: 96, title: "Лестница вместо лифта", description: "Если этаж ниже 5, поднимитесь пешком. Запишите пульс до и после.", difficulty: "easy", category: "health" },
{ id: 97, title: "Зрительная гимнастика", description: "Каждые 30 минут за экраном смотрите в окно на дальний объект (дерево, дом) 20 секунд. Делайте 2 часа.", difficulty: "easy", category: "health" },
{ id: 98, title: "Одно дело", description: "Делайте одно дело в течение 25 минут без переключения. Телефон в другой комнате.", difficulty: "middle", category: "productivity" },
{ id: 99, title: "Чек-лист утра", description: "Составьте чек-лист из 3 утренних ритуалов на завтра. Выполните и вычеркните.", difficulty: "easy", category: "productivity" },
{ id: 100, title: "Новый навык 15 минут", description: "Потратьте 15 минут на изучение нового мелкого навыка (завязать галстук, 3 фразы на новом языке, скороговорка).", difficulty: "easy", category: "productivity" },
{ id: 101, title: "Разбор рабочего стола", description: "Уберите всё лишнее с рабочего стола. Оставьте только то, чем пользуетесь ежедневно.", difficulty: "easy", category: "productivity" },
{ id: 102, title: "Одна сложная задача", description: "Выберите задачу, которую откладываете больше 2 недель. Сделайте только первый шаг (открыть документ, позвонить, написать первое предложение).", difficulty: "middle", category: "productivity" },
{ id: 103, title: "Правило 2 минут", description: "Найдите 3 дела, которые займут меньше 2 минут (помыть кружку, ответить на письмо, протереть пыль). Сделайте их немедленно.", difficulty: "easy", category: "productivity" },
{ id: 104, title: "Чтение без остановки", description: "Прочитайте 10 страниц любой книги без отвлечений на телефон, мысли о другом, перечитывание.", difficulty: "easy", category: "productivity" },
{ id: 105, title: "Список не-дел", description: "Составьте список из 5 вещей, которые вы сегодня НЕ будете делать (не проверять соцсети до обеда, не жаловаться).", difficulty: "easy", category: "productivity" },
{ id: 106, title: "Объясни проще", description: "Объясните сложную тему (из вашей работы/учебы) так, будто ребёнку 8 лет. Без жаргона.", difficulty: "middle", category: "productivity" },
{ id: 107, title: "Таймер на соцсети", description: "Поставьте таймер на 10 минут для соцсетей. Когда прозвенит — закройте и не заходите 2 часа.", difficulty: "hard", category: "productivity" },
{ id: 108, title: "Карта мыслей", description: "Нарисуйте интеллект-карту (mind map) для любой проблемы, которая вас беспокоит.", difficulty: "middle", category: "productivity" },
{ id: 109, title: "Замени скроллинг", description: "Вместо скроллинга ленты сделайте 5 отжиманий или 10 приседаний. В следующий раз, когда потянетесь к телефону, вспомните.", difficulty: "easy", category: "productivity" },
{ id: 110, title: "Конспект видео", description: "Посмотрите 10-минутное обучающее видео и напишите 3 главных тезиса своими словами.", difficulty: "easy", category: "productivity" },
{ id: 111, title: "Финансовая минута", description: "Откройте банковское приложение, посмотрите последние 5 трат. Одну трату оцените: 'было необходимо?'", difficulty: "easy", category: "productivity" },
{ id: 112, title: "Планирование вслух", description: "Проговорите вслух свой план на завтра по пунктам. Исследования говорят, что это повышает вероятность выполнения на 30%.", difficulty: "easy", category: "productivity" }
];
    localStorage.setItem('data', JSON.stringify(questDatabase))
}